services:
  db:
    image: postgres:15-alpine
    container_name: FindUrDrugz_Database
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Automatically runs scripts in this directory on first start
      - ./database/schema:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  pgdata: